version: 2.1

orbs:
  gradle: circleci/gradle@2.2.0

jobs:
  build:
    executor:
      name: gradle/default
      tag: '15.0.1'

    steps:
      - checkout

      - gradle/with_cache:
          steps:
            - run:
                name: Compile
                command: ./gradlew compileGroovy compileTestGroovy compileE2eGroovy

            - run:
                name: Test
                command: ./gradlew test

            - run:
                name: End-to-end
                command: ./gradlew e2e

            - run:
                name: Build
                command: ./gradlew build

  publish:
    executor:
      name: gradle/default
      tag: '15.0.1'

    steps:
      - checkout

      - gradle/with_cache:
          steps:
            - run:
                name: Build artifact
                command: ./gradlew jar

            - run:
                name: Publish plugin
                command: ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET

workflows:
  main:
    jobs:
      - build

      - publish:
          requires:
            - build
          filters:
            branches:
              only: release
