version: 2.1

executors:
  default-jvm:
    working_directory: ~/repo/strict-null-check

    docker:
      - image: circleci/openjdk:15-jdk-buster
        environment:
          JVM_OPTS: -Xmx4096m
          TERM: dumb

commands:
  setup:
    description: "Setup the environment to run tasks on CI"

    steps:
      - checkout:
          path: ~/repo/strict-null-check

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "plugin/buildscript-gradle.lockfile" }}-{{ checksum "plugin/gradle.lockfile" }}
            - v1-dependencies-{{ checksum "plugin/buildscript-gradle.lockfile" }}-
            - v1-dependencies-

  store-cache:
    description: "Store Gradle configuration and dependendies in cache"

    steps:
      - save_cache:
          paths:
            - ~/repo/strict-null-check/.gradle
            - ~/.gradle
          key: v1-dependencies-{{ checksum "plugin/buildscript-gradle.lockfile" }}-{{ checksum "plugin/gradle.lockfile" }}

jobs:
  build:
    executor: default-jvm

    steps:
      - setup

      - run:
          name: Compile
          command: ./gradlew compileGroovy compileTestGroovy compileE2eGroovy

      - run:
          name: Lint
          command: ./gradlew codenarcMain codenarcTest codenarcE2e

      - run:
          name: Test
          command: ./gradlew test

      - run:
          name: End-to-end
          command: ./gradlew e2e

      - run:
          name: Build
          command: ./gradlew build

      - store-cache

  publish:
    executor: default-jvm

    steps:
      - setup

      - run:
          name: Assemble
          command: ./gradlew assemble

      - run:
          name: Publish plugin
          command: ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
      
      - store-cache

workflows:
  main:
    jobs:
      - build

      - publish:
          requires:
            - build
          filters:
            branches:
              only: release
