version: 2.1

orbs:
  gradle: circleci/gradle@2.2.0

jobs:
  publish:
    executor:
      name: gradle/default
      tag: '15.0.1'

    steps:
      - checkout

      - gradle/with_cache:
          steps:
            - run:
                name: Build artifact
                command: ./gradlew jar

            - run:
                name: Publish plugin
                command: ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET

workflows:
  main:
    jobs:
      - gradle/test:
          executor:
            name: gradle/default
            tag: '15.0.1'
          test_command: build

      - publish:
          requires:
            - gradle/test
          filters:
            branches:
              only: release
