/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.github.joselion.strictnullcheck

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'com.github.joselion.strictnullcheck.greeting' plugin.
 */
class StrictNullCheckPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("com.github.joselion.strict-null-check")

        then:
        project.tasks.findByName("greeting") != null
    }
}
