name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_call:

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 21, 23]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: ${{ matrix.java }}
          check-latest: true
      - uses: gradle/actions/setup-gradle@v4
      - uses: gradle/actions/wrapper-validation@v4
      - uses: gradle/actions/dependency-submission@v4
      - run: ./gradlew compileJava compileTestJava compileTestkitJava
      - run: ./gradlew checkstyleMain checkstyleTest checkstyleTestkit
      - run: ./gradlew sonarlintMain sonarlintTest sonarlintTestkit
      - run: ./gradlew test
      - run: ./gradlew testkit
      - run: ./gradlew build
