---
name: CI

on:
  push:
  workflow_call:

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 20
          check-latest: true
          cache: gradle
      - run: ./gradlew compileGroovy compileTestGroovy compileE2eGroovy
      - run: ./gradlew codenarcMain codenarcTest codenarcE2e
      - run: ./gradlew test
      - run: ./gradlew e2e
      - run: ./gradlew build
