name: Auto approve for owner

on: pull_request

jobs:
  approve:
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: log
        env:
          CONTEXT: ${{ toJSON(github) }}
        run: echo "$CONTEXT"
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == github.repository_owner
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
