name: Auto approve for owner

on: pull_request

jobs:
  approve:
    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner && github.event.review.state != 'approved'
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
